GET http://0.0.0.0:3000/orangutan/survey/published HTTP/1.1

###
GET http://0.0.0.0:3000/orangutan/survey/published?firstname=Mathiew&lastname=Luther HTTP/1.1

###
GET http://0.0.0.0:3000/orangutan/survey/GeogrSurvey/detail HTTP/1.1

###
GET http://0.0.0.0:3000/orangutan/response/GeogrSurvey/count HTTP/1.1

###
POST http://0.0.0.0:3000/orangutan/response/GeogrSurvey/53ifnow HTTP/1.1
content-type: application/json

{
    "response": "answer1"
}

###
POST http://0.0.0.0:3000/orangutan/response/GeogrSurvey/kfj8392/otherResponse HTTP/1.1
Content-Type: application/json

{
    "response": "Ethiopia"
}

###
POST http://0.0.0.0:3000/orangutan/survey/IronSurvey/3455dds/create HTTP/1.1
Content-Type: application/json

{
    "status": "unpublished",
    "date_open": "2022-06-10T03:01:02.190+00:00",
    "date_close": "2022-07-10T07:00:00.000+00:00",
    "question": {
        "question": "What is the strongest metal",
        "answer1": "copper",
        "answer2": "silver",
        "answer3": "gold"
    }
}

###
PUT http://0.0.0.0:3000/orangutan/survey/IronSurvey/3455dds/status HTTP/1.1
Content-Type: application/json

{
    "status": "published"
}

###
PUT http://0.0.0.0:3000/orangutan/survey/IronSurvey/3455dds/question HTTP/1.1
Content-Type: application/json

{
    "question": "What is the most expensive metal"
}

###
POST http://0.0.0.0:3000/orangutan/response/IronSurvey/123abc HTTP/1.1
Content-Type: application/json

{
    "response": "answer1"
}

###
DELETE http://0.0.0.0:3000/orangutan/response/IronSurvey/3455dds/delete?firstname=Mathiew&lastname=Luther HTTP/1.1


###
DELETE http://0.0.0.0:3000/orangutan/survey/IronSurvey/3455dds/delete HTTP/1.1