GET http://0.0.0.0:3000/orangutan/survey/published HTTP/1.1

###
GET http://0.0.0.0:3000/orangutan/survey/published?firstname=Mathiew&lastname=Luther HTTP/1.1

###
GET http://0.0.0.0:3000/orangutan/survey/GeogrSurvey/detail HTTP/1.1

###
GET http://0.0.0.0:3000/orangutan/survey/GeogrSurvey/count HTTP/1.1

###
POST http://0.0.0.0:3000/orangutan/survey/GeogrSurvey/response
Content-Type: application/json
{
    'userId': '53ifnow',
    'response': 'Congo'
}

###
POST http://0.0.0.0:3000/orangutan/survey/GeogrSurvey/otherResponse
Content-Type: application/json
{
    'userId': 'kfj8392',
    'response': 'Ethiopia'
}

###
POST http://0.0.0.0:3000/orangutan/survey/IronSurvey/create
Content-Type: application/json
{
    'userId': '3455dds',
    'status': 'unpublished',
    'date_open': '2022-06-10T03:01:02.190+00:00',
    'date_close': '2022-07-10T07:00:00.000+00:00',
    'question': {
        'question': 'What is the strongest metal',
        'answer1': 'copper',
        'answer2': 'silver',
        'answer3': 'gold'
    }
}

###
PUT hhttp://0.0.0.0:3000/orangutan/survey/IronSurvey/updateStatus
Content-Type: application/json
{
    'ownerId': '3455dds',
    'status': 'published'
}

###
PUT hhttp://0.0.0.0:3000/orangutan/survey/IronSurvey/updateQuestion
Content-Type: application/json
{
    'ownerId': '3455dds',
    'question': 'What is the most expensive metal'
}

###
DELETE http://0.0.0.0:3000/orangutan/survey/IronSurvey/delete
Content-Type: application/json
{
    'ownerId': '3455dds',
    'firstname': 'Mathiew',
    'lastname': 'Luther'
}

###
DELETE http://0.0.0.0:3000/orangutan/survey/IronSurvey/deleteSurvey
Content-Type: application/json
{
    'ownerId': '3455dds',
}